
services:
- type: web
  name: Competitions-Platform.Red-Flags
  env: python
  repo: https://github.com/MadMoose02/Competitions-Platform
  plan: free
  branch: main
  healthCheckPath: /healthcheck
  buildCommand: "pip install -r requirements.txt"
  startCommand: "gunicorn wsgi:app"
  envVars:
  - fromGroup: Competitions-Platform-Settings
  - key: POSTGRES_URL
    fromDatabase:
      name: Competitions-Platform-DB.Red-Flags
      property: host
  - key: POSTGRES_USER
    fromDatabase:
      name: Competitions-Platform-DB.Red-Flags
      property: user
  - key: POSTGRES_PASSWORD
    fromDatabase:
      name:Competitions-Platform-DB.Red-Flags
      property: password
  - key: POSTGRES_DB
    fromDatabase:
      name: Competitions-Platform-DB.Red-Flags
      property: database 

envVarGroups:
- name: Competitions-Platform-Settings
  envVars:
  - key: ENV
    value: production
  - key: FLASK_APP
    value: wsgi.py
    

databases:
- name: Competitions-Platform-DB.Red-Flags
  plan: free
  databaseName: rfcp-db